### ISSUE TITLE
Got traceback when starting videogrep

### ISSUE THREAD

**Issue by urec56** [antiboredom/videogrep#134]
Command I start
```sh
videogrep --input "777.mp4" --search "meta"
```
result i get
```sh
Traceback (most recent call last):
  File "/mnt/urec/trash/some/all/PycharmProjects/VideoGrep2/.venv/bin/videogrep", line 8, in <module>
    sys.exit(main())
  File "/mnt/urec/trash/some/all/PycharmProjects/VideoGrep2/.venv/lib/python3.10/site-packages/videogrep/cli.py", line 153, in main
    videogrep(
  File "/mnt/urec/trash/some/all/PycharmProjects/VideoGrep2/.venv/lib/python3.10/site-packages/videogrep/videogrep.py", line 644, in videogrep
    segments = search(files, query, search_type)
  File "/mnt/urec/trash/some/all/PycharmProjects/VideoGrep2/.venv/lib/python3.10/site-packages/videogrep/videogrep.py", line 215, in search
    transcript = parse_transcript(file, prefer=prefer)
  File "/mnt/urec/trash/some/all/PycharmProjects/VideoGrep2/.venv/lib/python3.10/site-packages/videogrep/videogrep.py", line 79, in parse_transcript
    transcript = srt.parse(infile)
  File "/mnt/urec/trash/some/all/PycharmProjects/VideoGrep2/.venv/lib/python3.10/site-packages/videogrep/srt.py", line 66, in parse
    start, end = convert_timespan(line)
  File "/mnt/urec/trash/some/all/PycharmProjects/VideoGrep2/.venv/lib/python3.10/site-packages/videogrep/srt.py", line 16, in convert_timespan
    end = convert_timestamp(end)
  File "/mnt/urec/trash/some/all/PycharmProjects/VideoGrep2/.venv/lib/python3.10/site-packages/videogrep/srt.py", line 29, in convert_timestamp
    chunk, millis = timestamp.split(",")
ValueError: too many values to unpack (expected 2)
```

system: arch
kernel:  6.7.5-arch1-1
python: 3.10.10 and 3.11
videogrep==2.2.1
vosk==0.3.45
ffmpeg-2:6.1.1-6

**Comment by urec56** [comment]
OK. It was just wrong subtitles format in the end of the file
