### ISSUE TITLE
No module named '__main__.vtt'; '__main__' is not a package

### ISSUE THREAD

**Issue by raj6996** [antiboredom/videogrep#57]
I am using Win10, python 3.70, everything installed fine, but I got this, problem.
In CMD, I used>
SET PATH=%PATH%;O:\Python3.7\Lib\site-packages\videogrep
already .srt or .vtt subtitle on folder and subtitle is showing on vlc player.

G:\Python37\Lib\site-packages\videogrep>videogrep --input "G:\iG\bikini" --sea
rch 'auditions'
Traceback (most recent call last):
  File "G:\Python37\Lib\site-packages\videogrep\videogrep.py", line 14, in <modu
le>
    from .vtt import parse_auto_sub
ModuleNotFoundError: No module named '__main__.vtt'; '__main__' is not a package

G:\Python3.7\Lib\site-packages\videogrep>

Totally clueless! any help. thanks.

**Comment by raj6996** [comment]
> C:\Python37>python C:\Python37\myvideogrep.py -i "C:\A" --search "Not you" -o "C:\test.mp4"python C:\Python37\myvideogrep.py -i "C:\A" --search "Not you" -o "C:\test.mp4"
> usage: myvideogrep.py [-h] --input [INPUTFILE [INPUTFILE ...]]
>                       [--search SEARCH]
>                       [--search-type {re,pos,hyper,fragment,franken,word}]
>                       [--use-transcript] [--use-vtt] [--max-clips MAXCLIPS]
>                       [--output OUTPUTFILE] [--export-clips] [--demo]
>                       [--randomize] [--youtube YOUTUBE] [--padding PADDING]
>                       [--resyncsubs SYNC] [--transcribe] [--ngrams NGRAMS]
> myvideogrep.py: error: unrecognized arguments: C:\Python37\myvideogrep.py
>  
> C:\Python37>python C:\Python37\myvideogrep.py -i "G:\I" -s "All" -st word -o test.mp4
> [!] No subtitle files were found.
> Traceback (most recent call last):
>   File "C:\Python37\myvideogrep.py", line 3, in <module>
>     videogrep.main()
>   File "C:\Python37\lib\site-packages\videogrep\videogrep.py", line 528, in main
>     videogrep(args.inputfile, args.outputfile, args.search, args.searchtype, args.maxclips, args.padding, args.demo, args.randomize, args.sync, args.use_transcript, args.use_vtt, args.export_clips)
>   File "C:\Python37\lib\site-packages\videogrep\videogrep.py", line 456, in videogrep
>     composition = compose_from_srts(srts, search, searchtype)
>   File "C:\Python37\lib\site-packages\videogrep\videogrep.py", line 317, in compose_from_srts
>     for srt in srts:
> TypeError: 'bool' object is not iterable
> 

Hey anyone tested videogrep in Windows 10, I got new error. plz fix it. thanks.
#48
